sudo: required

language: java

jdk: openjdk11

git:
  depth: 9999999

before_script:
  - bash ./.travis/install-postgres-11.sh

services:
  - docker
  - postgresql

script:
  - ./gradlew build sonarqube